config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    delete 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :exit_user_session
    get 'users/sessions/failed'
  end
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :points
  resources :events do
    member do
      get :qr
      get :join
    end
    collection do
      get :join, to: 'events#join_by_code'
      post :join, to: 'events#join_by_code'
    end
  end
  post '/checkin', to: 'events_users#create'
  get '/moon', to: 'application#moon', as: 'moon' # dark mode
  get '/sun', to: 'application#sun', as: 'sun' # light mode
  get '/qr/:code', to: 'events#raw_qr'
  get '/users/search'
  get '/users/show'
  post '/users/import'
  get '/contacts/search'
  get '/contacts', to: 'contacts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'events#index'
end

app/views/layouts/_eventcode_modal.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <!--        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>-->
      <h4 class="modal-title" id="myModalLabel">Event Code</h4>
    </div>
    <div class="modal-body">
      <form accept-charset="UTF-8" action="/events/join" method="post">
        <label>
          Enter the meeting code
          <input type="text" name="event[eventCode]" value=""/>
        </label>
        <br/>
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
        <button type="submit" class="btn btn-primary">Check In</button>
      </form>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="d-flex flex-row w-100 justify-content-between nav-container">
  <a class="p-2 w-100 text-center nav-link" href="/events">Events</a>
  <%= link_to 'Points', "/users/search", class: "p-2 w-100 text-center nav-link" %>
  <a class="p-2 w-100 text-center nav-link" href="/contacts/search">Contacts</a>
  <a class="p-2 w-100 text-center nav-link" href="/User-Manual">Help</a>
  <a class="p-2 w-100 text-center nav-link nav-link-admin" href="/admin">Admin</a>
</div>

app/views/layouts/_splash.html.erb
<div class="home-splash d-flex justify-content-center align-items-center text-center">
    <div class="p-2">
        <%# <h1>ANS Points</h1> %>
        <div class="main-logo">
            <a href="/events"> 
                <%= image_tag("light_logo_ans_points.png", :class => "logo-image") %>
            </a>
        </div>
    </div>

</div>
<div class="position-fixed top-0 end-0" style="margin: 10px">
    <% if cookies[:moon] == 'true' %>
        <%= button_to '', sun_path, method: :get, class: 'sun' %>
    <% else %>
        <%= button_to '', moon_path, method: :get, class: 'moon' %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ANS Points</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% if cookies[:moon] == 'true' %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= stylesheet_link_tag 'application_dark', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% end %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
        .flash__alert   { color: black; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
  </head>

  <body>
    <%= render "layouts/splash" %>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
  <script src="https://code.responsivevoice.org/responsivevoice.js?key=v9Vnt0at"></script>
</html>